### PR TITLE
Rewrite the item page of the storage docs

### LINKED ISSUE #50: Rewrite `Item`
Move toward more use-case-driven docs, probably!

### PR DESCRIPTION
**Pull request by aumetra**
Closes #50

### CODE REVIEW

**Comment by aumetra** [comment]
This is still very barebones and might need some more examples. Most I did for now was reword the entire "chapter" and change the formatting

**Review by hashedone — COMMENTED** [review]
Added some comments in vercel

**Review by uint — APPROVED** [review]
Looks like the main change is explaining the fact an `Item` might be "empty" more clearly? Sounds good.

I'd still keep the link to the API ref around, ~~or mention an item might be [`remove`d](https://docs.rs/cw-storage-plus/latest/cw_storage_plus/struct.Item.html#method.remove)~~ (missed that it's there already).

**Comment by aumetra** [comment]
> Looks like the main change is explaining the fact an Item might be "empty" more clearly? Sounds good.

Yeah, that and some miscellaneous wording changes, and structuring the page a bit differently. Otherwise I haven't seen any other things that might need changing.

**Pull request merged**
